# Generated by Django 2.0.8 on 2018-09-22 23:55

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='aboutMe',
            field=wagtail.core.fields.RichTextField(default='alex'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='aboutThisWebsite',
            field=wagtail.core.fields.RichTextField(default='alex'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='homePageMessage',
            field=wagtail.core.fields.RichTextField(default='alex'),
        ),
    ]
